default_stages: [pre-commit, pre-push]
fail_fast: true

repos:
  # --- Basic hygiene checks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: pretty-format-json
        args: [--autofix, --indent, "2"]

  # --- Ruff (linting & autofix) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        stages: [pre-push]   # run linting only before push for speed

  # --- Mypy (static type checker) ---
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [--strict, --show-error-codes]
        stages: [pre-push]   # run type-checking only before push

# --- CI integration (if using pre-commit.ci) ---
ci:
  autofix_prs: true
  autoupdate_schedule: weekly
